### PR TITLE
telegraf: replace sudo with setuid wrapper for telegraf

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by zowoq** [comment]
```
Read NVMe Identify Controller failed: NVME_IOCTL_ADMIN_CMD: Permission denied
```

**Comment by Mic92** [comment]
Does this error come from the nvme command or from smartctl?

**Comment by zowoq** [comment]
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/smart

`smartctl`, I ran the plugin commands manually.

With this branch 01 has full data but on 02/03 the data is incomplete.

**Comment by Mic92** [comment]
needs CAP_SYS_ADMIN: https://github.com/torvalds/linux/blob/1b907d0507354b74a4f2c286380cd6059af79248/drivers/nvme/host/ioctl.c#L21

**Comment by zowoq** [comment]
Thank you.

**Pull request merged**
