### PR TITLE
ci: restore GitHub Actions

### PR DESCRIPTION
**Pull request by zimbatm**
This is a subset that should work (it's going to be slow though)

### CODE REVIEW

**Comment by zimbatm** [comment]
I see the namespace.so ran out of memory: https://cloud.namespace.so/4l6g3pb71m64u/cluster/rfn8s20s5hh78
image

**Comment by zimbatm** [comment]
the server VM test is super slow

**Comment by Mic92** [comment]
We can just expose our nixos tests in `.#checks` for now and leave the rest for the github CI.
I am thinking about how I can make buildbot reading a configuration file to make build outputs and subdirs configurable.

**Comment by zimbatm** [comment]
good idea

**Pull request closed without merging**
