### PR TITLE
openssh: disable SFTP by default

### PR DESCRIPTION
**Pull request by zimbatm**
Also inspired by https://xeiaso.net/blog/paranoid-nixos-2021-07-18/

### CODE REVIEW

**Comment by Mic92** [comment]
I feel like I would use this feature too often to have it disabled and an attacker that has ssh access also can extract files, so I don't see a significant security win.

**Comment by zimbatm** [comment]
Ok

**Comment by zimbatm** [comment]
Just to be sure; this is SFTP, not scp

**Comment by phaer** [comment]
`scp`, the tool, uses SFTP under the hood since [OpenSSH 9.0](https://www.openssh.com/txt/release-9.0). Disabling SFTP would require use of the legacy scp protocol

**Pull request closed without merging**
